[ERROR][models.go:40]2019/11/20 11:02:42 [dial tcp: lookup tcp/数据库端口号: Servname not supported for ai_socktype]
[INFO][test.go:26]2019/11/20 11:02:42 [Server err: %v net.Listen error: listen tcp :8080: bind: address already in use]
[ERROR][models.go:40]2019/11/20 11:11:43 [dial tcp: lookup tcp/数据库端口号: Servname not supported for ai_socktype]
[INFO][test.go:22]2019/11/20 11:11:43 [Actual pid is %d 27312]
[ERROR][models.go:40]2019/11/20 11:11:57 [dial tcp: lookup tcp/数据库端口号: Servname not supported for ai_socktype]
[INFO][test.go:22]2019/11/20 11:11:57 [Actual pid is %d 27334]
[INFO][test.go:26]2019/11/20 11:11:57 [Server err: %v accept tcp [::]:8080: use of closed network connection]
[ERROR][models.go:40]2019/11/20 11:17:27 [dial tcp: lookup tcp/数据库端口号: Servname not supported for ai_socktype]
[INFO][test.go:22]2019/11/20 11:17:27 [Actual pid is %d 27812]
[ERROR][models.go:40]2019/11/20 11:18:09 [dial tcp: lookup tcp/数据库端口号: Servname not supported for ai_socktype]
[INFO][test.go:22]2019/11/20 11:18:09 [Actual pid is %d 27838]
[INFO][test.go:26]2019/11/20 11:18:09 [Server err: %v accept tcp [::]:8080: use of closed network connection]
[ERROR][models.go:40]2019/11/20 11:18:42 [dial tcp: lookup tcp/数据库端口号: Servname not supported for ai_socktype]
[INFO][test.go:22]2019/11/20 11:18:42 [Actual pid is %d 27977]
[ERROR][models.go:40]2019/11/20 11:18:54 [dial tcp: lookup tcp/数据库端口号: Servname not supported for ai_socktype]
[INFO][test.go:22]2019/11/20 11:18:54 [Actual pid is %d 27990]
[INFO][test.go:26]2019/11/20 11:18:54 [Server err: %v accept tcp [::]:8080: use of closed network connection]
[ERROR][models.go:40]2019/11/20 18:59:07 [dial tcp: lookup tcp/数据库端口号: Servname not supported for ai_socktype]
[INFO][main.go:22]2019/11/20 18:59:07 [Actual pid is %d 5240]
[INFO][main.go:26]2019/11/20 18:59:10 [Server err: %v accept tcp [::]:8080: use of closed network connection]
